services:
  - type: web
    name: jmaas-app
    env: node
    region: oregon
    plan: free
    rootDir: JMaaS_2ndsem_miniprj-main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
